---
- name: Install Apigee component with proxy - {{ component }}
  shell: '{{ apigee_service }} {{ component }} install'
  executable: /usr/bin/bash
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: DEBUG_MODE - Install Apigee component - {{ component }}
  shell: '/usr/bin/bash -x {{ apigee_service }} {{ component }} install'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

