---
- name: Install Apigee component with proxy - {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} install'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: DEBUG_MODE - Install Apigee component - {{ component }}
  command: '/bin/bash -x /opt/apigee/apigee-service/bin/apigee-service {{ component }} install'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

