---
- name: Setup utilities in cache
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'apigee_home', value: "{{ apigee_home }}" }
  - { key: 'apigee_setup', value: "{{ apigee_setup }}" }
  - { key: 'apigee_all', value: "{{ apigee_all }}" }

- name: Install Apigee component {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} install'
  args:
    creates: "{{ apigee_home }}/{{ component }}"
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: DEBUG_MODE - Install Apigee component {{ component }}
  command: '/bin/bash -x /opt/apigee/apigee-service/bin/apigee-service {{ component }} install'
  args:
    creates: "{{ apigee_home }}/{{ component }}"
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

