---
- name: Install Apigee component with no proxy - {{ component }}
  shell: '{{ apigee_service }} {{ component }} install'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'
  args:
    executable: /bin/bash

- name: DEBUG_MODE - Install Apigee component with no proxy - {{ component }}
  shell: '{{ apigee_service }} {{ component }} install'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'
  args:
    executable: /bin/bash
