---
- name: Install Apigee component with proxy - {{ component}}
  shell: '{{ apigee_service }} {{ component }} install'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
